interface IssueBase {
  reason: string;
  /** Stack of issues with more details. */
  issues?: Issue[];
  /** Current `index` or `key` where the issue was generated. */
  position?: unknown;
}

/** Received type is not the expected. */
export interface IssueType extends IssueBase {
  reason: "TYPE";
  /** The expected type. */
  expected: unknown;
  /** The received type. */
  received?: unknown;
}

/** Received value does not fulfill the constraint. */
export interface IssueValidation extends IssueBase {
  reason: "VALIDATION";
  /** The validation that was not fulfilled. */
  validation?: string;
  /** The expected value. */
  expected?: unknown;
  /** The received value. */
  received?: unknown;
}

/** Expect one value but no one was received. */
export interface IssueMissing extends IssueBase {
  reason: "MISSING";
}

/** Expect no value but one was received. */
export interface IssuePresent extends IssueBase {
  reason: "PRESENT";
}

/**
 * Issue that can be generated by the library.
 */
export type Issue = Readonly<
  IssueType | IssueValidation | IssueMissing | IssuePresent
>;
