name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  spelling:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check for spelling
        uses: crate-ci/typos@v1.23.2
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup "Deno v1"
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ hashFiles('deno.lock') }}
          path: |
            ~/.deno
            ~/.cache/deno

      - name: Run formatting checks
        run: deno task ok:format

      - name: Run typing checks
        run: deno task ok:types

      - name: Run linting checks
        run: deno task ok:lint

      - name: Run unit-test cases
        run: deno task ok:unit

      - name: Check pre-publish
        run: deno task ok:publish
